apiVersion: v1
kind: ServiceAccount
metadata:
  name: http-source-controller-manager
  namespace: http-source

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: http-source-controller
rules:
# Sources admin
- apiGroups:
  - sources.knative.dev
  resources:
  - samplesources
  verbs: &everything
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

# Source statuses update
- apiGroups:
  - sources.knative.dev
  resources:
  - samplesources/status
  verbs:
  - get
  - update
  - patch

# Deployments admin
- apiGroups:
  - apps
  resources:
  - deployments
  verbs: *everything

# Channels and Brokers read
- apiGroups:
  - eventing.knative.dev
  resources:
  - channels
  - brokers
  verbs: &readOnly
  - get
  - list
  - watch

# Knative Services admin
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs: *everything

# Secrets read
- apiGroups:
  - ""
  resources:
  - secrets
  verbs: *readOnly

# Events admin
- apiGroups:
  - ""
  resources:
  - events
  verbs: *everything

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: http-source-controller
subjects:
- kind: ServiceAccount
  name: http-source-controller-manager
  namespace: http-source
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: http-source-controller
